ALTER TYPE "ClaimFrequencyCode" ADD VALUE IF NOT EXISTS 'INTERIM_FIRST';
ALTER TYPE "ClaimFrequencyCode" ADD VALUE IF NOT EXISTS 'INTERIM_CONTINUING';
ALTER TYPE "ClaimFrequencyCode" ADD VALUE IF NOT EXISTS 'INTERIM_LAST';
ALTER TYPE "ClaimFrequencyCode" ADD VALUE IF NOT EXISTS 'FINAL_HOME_HEALTH';
