export const PERMISSIONS = Object.freeze({
  CLAIM_VIEW: "CLAIM_VIEW",
  CLAIM_EDIT: "CLAIM_EDIT",
  PATIENT_IDENTITY_VIEW: "PATIENT_IDENTITY_VIEW",
  INSURANCE_VIEW: "INSURANCE_VIEW",
  CLINICAL_VIEW: "CLINICAL_VIEW",
  CLINICAL_EDIT: "CLINICAL_EDIT",
  FINANCIAL_VIEW: "FINANCIAL_VIEW",
  FINANCIAL_EDIT: "FINANCIAL_EDIT",
  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_DOWNLOAD: "DOCUMENT_DOWNLOAD",
  PAYER_CONNECT: "PAYER_CONNECT",
  PAYER_ACTION: "PAYER_ACTION",
  CLAIM_SUBMIT: "CLAIM_SUBMIT",
  DENIAL_VIEW: "DENIAL_VIEW",
  DENIAL_EDIT: "DENIAL_EDIT",
  RECOVERY_EDIT: "RECOVERY_EDIT",
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  USER_ADMIN: "USER_ADMIN"
});

export function hasPermission(user, permission) {
  return Array.isArray(user?.permissions) && user.permissions.includes(permission);
}
