export const PERMISSIONS = Object.freeze({
  CLAIM_VIEW: "CLAIM_VIEW",
  CLAIM_EDIT: "CLAIM_EDIT",
  CLAIM_DELETE: "CLAIM_DELETE",
  PATIENT_IDENTITY_VIEW: "PATIENT_IDENTITY_VIEW",
  INSURANCE_VIEW: "INSURANCE_VIEW",
  CLINICAL_VIEW: "CLINICAL_VIEW",
  FINANCIAL_VIEW: "FINANCIAL_VIEW",
  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_DOWNLOAD: "DOCUMENT_DOWNLOAD",
  PAYER_ACTION: "PAYER_ACTION",
  CLAIM_SUBMIT: "CLAIM_SUBMIT",
  DENIAL_VIEW: "DENIAL_VIEW",
  DENIAL_EDIT: "DENIAL_EDIT",
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_EXPORT: "AUDIT_EXPORT",
  USER_ADMIN: "USER_ADMIN"
});

const ROLE_PERMISSIONS = Object.freeze({
  ADMIN: new Set([
    PERMISSIONS.CLAIM_VIEW,
    PERMISSIONS.CLAIM_EDIT,
    PERMISSIONS.CLAIM_DELETE,
    PERMISSIONS.PATIENT_IDENTITY_VIEW,
    PERMISSIONS.INSURANCE_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.FINANCIAL_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.PAYER_ACTION,
    PERMISSIONS.CLAIM_SUBMIT,
    PERMISSIONS.DENIAL_VIEW,
    PERMISSIONS.DENIAL_EDIT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.USER_ADMIN
  ]),
  CASHIER: new Set([
    PERMISSIONS.CLAIM_VIEW,
    PERMISSIONS.CLAIM_EDIT,
    PERMISSIONS.CLAIM_DELETE,
    PERMISSIONS.PATIENT_IDENTITY_VIEW,
    PERMISSIONS.INSURANCE_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.FINANCIAL_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.PAYER_ACTION,
    PERMISSIONS.CLAIM_SUBMIT,
    PERMISSIONS.DENIAL_VIEW,
    PERMISSIONS.DENIAL_EDIT
  ]),
  RECEPTIONIST: new Set([
    PERMISSIONS.CLAIM_VIEW,
    PERMISSIONS.CLAIM_EDIT,
    PERMISSIONS.PATIENT_IDENTITY_VIEW,
    PERMISSIONS.INSURANCE_VIEW
  ])
});

export function permissionsForRole(role) {
  return new Set(ROLE_PERMISSIONS[String(role || "").toUpperCase()] || []);
}

export function hasPermission(userOrRole, permission) {
  const role =
    typeof userOrRole === "string" ? userOrRole : userOrRole?.role;
  return permissionsForRole(role).has(permission);
}

export function permissionList(userOrRole) {
  return [...permissionsForRole(
    typeof userOrRole === "string" ? userOrRole : userOrRole?.role
  )];
}
